### ISSUE TITLE
Black screen after Apple logo

### ISSUE THREAD

**Issue by fedecarroz** [johnnync13/XiaomiGaming#100]
I just did a clean installation of Mac OS Big Sur 11.6 and everything work fine, except for a little problem. When I turn on the pc i see the Apple logo with the loading bar, but after a few seconds the screen turns off. After 3/4 minutes it turns on again with the login screen. After that I can log in normally but I want to fix this problem.

In order to fix wifi I tried ti replace AirportItlwm.kext with Itlwn.kext. After that the problem of the black screen was solved, but the wifi was still not working. So I replaced Itlwn.kext with the updated version of AirportItlwm.kext (the one for big sur) and after that the problem of the black screen came up again, but, at least, wifi now works perfectly.

Sorry for the long message, I hope you can help me.

**Comment by vovazubko** [comment]
Hi guys!
You can try my package. 
Hope it helps you.

https://github.com/vovazubko/XiaomiGaming

**Comment by fedecarroz** [comment]
I found the solution:

- Upgrade OpenCore version to the latest version
- Update WhateverGreen kext to the latest version
- Modify config.plist and add into "boot args" this: -igfxblr
- Save all in the main EFI folder, then restart
