### ISSUE TITLE
另一个硬盘里安装的Win10不在启动项里显示了

### ISSUE THREAD

**Issue by dddpc** [johnnync13/XiaomiGaming#101]
小米游戏本8代CPU。多硬盘。硬盘1安装有Win10，将10.15安装在了另一个硬盘里。但是现在Win10不在启动项里了。开机F12也看不到。请问这该怎么处理啊？

**Comment by eilidan** [comment]
用u盘做个pe修复一下应该能解决，我昨天才单硬盘双系统成功
