### ISSUE TITLE
Hello, how do you solve the sleep/wake problem?

### ISSUE THREAD

**Issue by kirainmoe** [johnnync13/XiaomiGaming#12]
I have a i7-8750H laptop and everything is working fine except the sleep/wake feature. I have tried several solutions I could find from Google but none of them works.

When I click Apple->Sleep, my laptop screen gets black but cpus are still working. After several seconds, I can't wake it up anymore because once it is waked it stuck. 

From tonymacx86 forum I found your 8750H laptop was working well, including the sleep/awake . I think that there may be some similarities in 8th gen laptop so I'm wondering:

1. Did your sleep/wake just work well after you install the Mojave?
2. If not, what you did to make it work?
3. I had checked "Generate Plugin Type" in my Clover ACPI. Is there anything else I should do to activate the native power management?

Thank you so much.

**Comment by kirainmoe** [comment]
Finally I solved the problem by injecting USB ports and patching _PRW.

**Comment by JohnyFW** [comment]
I'm very happy, I was going to write you that I did not do anything weird, just copy the EFI of johnny and follow a tutorial of creating USB to install mojave
