### ISSUE TITLE
driver for GTX1060

### ISSUE THREAD

**Issue by gangbanbro** [johnnync13/XiaomiGaming#13]
hi johnny .I'm a Chinese user.We have  a chat group(QQ) about install MAC OS on XiaoMiGaming, and some people try to drive GTX1060 , but all failed .do you have some idea about to solve this?
Thank you so much.

**Comment by johnnync13** [comment]
If bios not have option to desactivate GTX is that use Nvidia Optimus that is not compatible with macOS 
@gangbanbro

**Comment by gangbanbro** [comment]
but xiaomiGaming laptop with i7 7700hq can drive nvidia gpu. Is there anything special?

**Comment by gangbanbro** [comment]
i have asked someone in your chat group send the efi to you.
