### ISSUE TITLE
is your stock ssd pm981？is it compatible？or you just add a extra sata ssd？

### ISSUE THREAD

**Issue by SINOPW** [johnnync13/XiaomiGaming#17]

**Comment by JohnyFW** [comment]
use this samsung ssd 960 evo nvme m.2, the default disk NVME of laptop its not compatible

**Comment by SINOPW** [comment]
> use this samsung ssd 960 evo nvme m.2, the default disk NVME of laptop its not compatible
thanks for your explanation and how should I modify this efi if I use a sata ssd？

**Comment by SINOPW** [comment]
> use this samsung ssd 960 evo nvme m.2, the default disk NVME of laptop its not compatible

thanks for your explanation and how should I modify this efi if I use a sata ssd？should I delete some kext？

**Comment by JohnyFW** [comment]
Sorry,I have in one m2 i have Osx, other m2 to Windows, and sata ssd with extra space.

I think the only thing you do not have to have connected are the incompatible disks connected to the laptop

**Comment by SINOPW** [comment]
> Sorry,I have in one m2 i have Osx, other m2 to Windows, and sata ssd with extra space.
> 
> I think the only thing you do not have to have connected are the incompatible disks connected to the laptop

thank you very much

**Comment by JohnyFW** [comment]
really enjoy your hakintosh :D
