### ISSUE TITLE
Temperature Sensors Broken

### ISSUE THREAD

**Issue by dizhenhuoshan** [johnnync13/XiaomiGaming#18]
Hi, johnnync13, the temperature sensors didn't work after using the newest EFI. 

I have tried many softwares such as turbe switcher and istatmenu, and when I changed the EFI to another version they works. So I think it's the EFI's problem.

By the way, the trackpad is wonderful! Really a good job! :)

**Comment by SINOPW** [comment]
use sensor kext here,it
 will be
 finehttps://github.com/acidanthera/VirtualSMC

**Comment by dizhenhuoshan** [comment]
> use sensor kext here https://github.com/acidanthera/VirtualSMC

I think it's the drivers for VirtualSMC, but this EFI uses FakeSMC instead.
I have tried replace FakeSMC by VirtualSMC but failed.

**Comment by dizhenhuoshan** [comment]
Solved by using the FakeSMC Sensors Driver here
[https://bitbucket.org/RehabMan/os-x-fakesmc-kozlek](url)
