### ISSUE TITLE
Problems with this EFI clover configuration

### ISSUE THREAD

**Issue by wizcheu** [johnnync13/XiaomiGaming#2]
Hi, the specs of my XiaomiGaming Laptop is **i7-8750h, GTX 1060** and my macos version is **10.14.2 (18C54)**, when using your configuration, I've met problems that not working(in your readme, you said that's ok) as below:
- USB 3.0
- Audio
- Bluetooth
- Brightness hot key
- Trackpad(not so sensitive)
- Direct HDMI video and audio(but USB-C to HDMI is ok)

**Comment by liangenze1993** [comment]
你好，我是来自中国的小米游戏本八代的黑苹果用户，很高兴能和你交流。
我们这边也在研究小米游戏本八代，MACos，i7-8750h，GTX 1060如果有兴趣 加一下qq群
请问您这个EFI   MAC14.2系统使用正常吗？我们中国这边的睡眠会黑屏无亮度。
如果有兴趣 加一下qq群   QQ群号：948983755  个人QQ：185282901   WeChat ：185282901
[小米游戏本8代顶配版USBC转HDMI输出外接显示器CloverEFI.zip](https://github.com/johnnync13/XiaomiGaming/files/2714335/8.USBC.HDMI.CloverEFI.zip)

我们可以分享我们的EFI更多的是一起交流

**Comment by liangenze1993** [comment]
[14_CLOVER.zip](https://github.com/johnnync13/XiaomiGaming/files/2714340/14_CLOVER.zip)
[小米八代游戏本原亮度快捷键.zip](https://github.com/johnnync13/XiaomiGaming/files/2714344/default.zip)
[小米八代10.13.6 EFI最早小思绪的.zip](https://github.com/johnnync13/XiaomiGaming/files/2714346/10.13.6.EFI.zip)

**Comment by xymoc** [comment]
I am from China. I have been researching this Game computer recently, but I have encountered some problems, such as:

1. NVIDIA GTX1060 Standalone graphics cannot be driven.
2. Can't wake up the computer after computer sleep.
3. The touchpad does not support gestures.
4. WIFI cannot be used.
5. Bluetooth can only be used when Windows restart to MacOS.

If can get your help, I can provide the Clover I use.
