### ISSUE TITLE
Touchpads are sometimes unavailable

### ISSUE THREAD

**Issue by Kurokitu** [johnnync13/XiaomiGaming#22]
Sometimes the touch pad can't be detected.

**Comment by Kurokitu** [comment]
V3.6 version in the new installation is a prohibition flag, i7-8th

**Comment by johnnync13** [comment]
change virtualsmc to fakesmc

**Comment by Kurokitu** [comment]
I found that XHCI and USBInjectAll seemed to be the cause. When I disabled USBInjectAll, the boot was normal.

**Comment by Kurokitu** [comment]
But even version 3.8 will be Black-screen if it does not add "-v" at boot time.

**Comment by Kurokitu** [comment]
The detection is completed. The black screen is due to a problem with the backlight driver during boot loading.

**Comment by dizhenhuoshan** [comment]
> The detection is completed. The black screen is due to a problem with the backlight driver during boot loading.

I have tried the v3.8 release and failed to install. The installer said that there was an error and reboot is needed. I wonder how to install it with v3.8...

**Comment by dizhenhuoshan** [comment]
By the way, I found that battery drains much faster in hackintosh than in Windows. Is there any solutions? (My battery life is 1.5 hours in macOS and almost 3 hours in Windows, I think there may be something wrong in battery driver?

**Comment by johnnync13** [comment]
use this @dizhenhuoshan https://github.com/stevezhengshiqi/one-key-cpufriend

**Comment by johnnync13** [comment]
I don't understand because not works good virtualsmc on this laptop, it is better than old fakesmc. I use usbinjectall because I need to use teamviewer with another user that has this laptop
