### ISSUE TITLE
Clean install 10.14.5 failed

### ISSUE THREAD

**Issue by dizhenhuoshan** [johnnync13/XiaomiGaming#23]
Hi, johnnync13
I have tried to clean install 10.14.5 using the newest EFI v3.6. The installer from usb device successfully finished. However when I reboot to finish the system installation I stuck with the apple logo with an empty progress bar. 
I have tried the verbose mode and logs can be printed normally, but still stuck with the apple logo.
Hope you could give some help, thank you :)

**Comment by johnnync13** [comment]
change virtualsmc to fakesmc

**Comment by dizhenhuoshan** [comment]
FakeSMC(EFI release v3.1) works fine on my laptop. Is VirtualSMC not stable enough? Or I have some wrong configs?

**Comment by johnnync13** [comment]
I don't know why not works good virtualsmc on this laptops it is better than old fakesmc
