### ISSUE TITLE
I fixed some problems and created merged branches. Are there any problems you can solve?

### ISSUE THREAD

**Issue by Kurokitu** [johnnync13/XiaomiGaming#25]
At present, I have repaired some things and submitted a merge. If you think it's OK, you can merge the projects. And at present, FN brightness adjustment can not be used, can you help me repair it?Thank you!

**Comment by johnnync13** [comment]
you should use acpidebug and see what key you use. And on DSDT you have some keys configuration

**Comment by Kurokitu** [comment]
In addition, the microphone only works when the headset is inserted. I'm looking for a solution.
