### ISSUE TITLE
Can not connect to the external monitor

### ISSUE THREAD

**Issue by dizhenhuoshan** [johnnync13/XiaomiGaming#29]
I have tested the type-c and HDMI ports. When I connected the monitor to the type ports, my laptop reboot immediately. When I connected the monitor to the HDMI ports there was nothing happened and my monitor said  "there is no signal from the HDMI cable".

For the type-C port, I think it is using DP protocol. Also, I tried to use hackintool to fix it (I have tried both DP and HDMI protocol with platform-ID 0x3E9B0000 ), but when I plugged in the cable the laptop still immediately reboot.

For the HDMI port, I think may be it's connected to the Nvidia GPU and I can not drive it ?

Really thanks for your devoting !

**Comment by johnnync13** [comment]
@dizhenhuoshan try this! https://github.com/johnnync13/XiaomiGaming/releases/tag/v4.1

**Comment by ROXy10** [comment]
@johnnync13 Don't work(

**Comment by dizhenhuoshan** [comment]
Release V4.1 does not work. However, when I connect the type-c monitor, the laptop does not reboot. Still, my monitor says that there is no signal.
Also, I have confirmed that the HDMI port is connected to the NVIDIA GPU, and we can not use it until we drive NVIDIA GPU succefully.
This EFI [https://github.com/dizhenhuoshan/XiaoMiGaming-8th-Hackintosh](url) can use external   monitor but it is very different from yours. Maybe we can merge them to get a better one?

**Comment by johnnync13** [comment]
for me no problem!

**Comment by johnnync13** [comment]
@dizhenhuoshan @Kurokitu  try to fix audio with correct codec and pins
this is the tutorial to custom config to applealc 
https://blog.daliansky.net/Use-AppleALC-sound-card-to-drive-the-correct-posture-of-AppleHDA.html

**Comment by dizhenhuoshan** [comment]
> @dizhenhuoshan @Kurokitu try to fix audio with correct codec and pins
> this is the tutorial to custom config to applealc
> https://blog.daliansky.net/Use-AppleALC-sound-card-to-drive-the-correct-posture-of-AppleHDA.html

I will try it, thank you!!!
