### ISSUE TITLE
你好，我是来自中国的小米游戏本八代的黑苹果用户，很高兴能和你交流。

### ISSUE THREAD

**Issue by liangenze1993** [johnnync13/XiaomiGaming#3]
你好，我是来自中国的小米游戏本八代的黑苹果用户，很高兴能和你交流。
[【目前较完善】8代支持睡眠 ，但启动黑屏.zip](https://github.com/johnnync13/XiaomiGaming/files/2714352/8.zip)
[小米八代10.13.6 EFI最早小思绪的.zip](https://github.com/johnnync13/XiaomiGaming/files/2714353/10.13.6.EFI.zip)
[14_CLOVER.zip](https://github.com/johnnync13/XiaomiGaming/files/2714354/14_CLOVER.zip)
[8代顶配USBC转外接显示USB3.0可用CloverEFI.zip](https://github.com/johnnync13/XiaomiGaming/files/2714355/8.USBC.USB3.0.CloverEFI.zip)

我们这边也在研究小米游戏本八代，MACOS，i7-8750h，GTX 1060如果有兴趣加一下qq群
请问您这个EFI MAC14.2系统使用正常吗？我们中国这边的睡眠会黑屏无亮度。
如果有兴趣加一下qq群QQ群号：948983755个人QQ：185282901微信号：185282901

**Comment by johnnync13** [comment]
Use english please. If you don't speak, use google translate

**Comment by johnnync13** [comment]
There are some error in your EFIs. 
you combine the daliansky efi and he has 7700hq, the Xiaomi Gaming First Version
