### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by VitalyArt** [johnnync13/XiaomiGaming#32]
Xiaomi Gamin Laptop Gen2
MacOS: Catalina 15.10.3
CPU: i7-8750h

v5.0 - ok
v5.1 - ok
v5.2 - black screen
v5.3 - black screen

https://www.youtube.com/watch?v=ddjGJe4n8m0

**Comment by johnnync13** [comment]
@Andrey1970AppleLife I have this issue with VirtualSMC on Xiaomi Gaming Laptop 8750h. With FakeSMC, the laptop works fine..!

**Comment by johnnync13** [comment]
try the last release @VitalyArt

**Comment by VitalyArt** [comment]
👍 I'll check after work and make sure I write

**Comment by johnnync13** [comment]
okey! @VitalyArt try https://github.com/johnnync13/XiaomiGaming/releases/tag/v5.6

**Comment by VitalyArt** [comment]
v5.2-v5.6 - black screen

**Comment by VitalyArt** [comment]
v5.1 works

**Comment by johnnync13** [comment]
v5.7 fix this!
