### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by Salvo092000** [johnnync13/XiaomiGaming#36]
hi, i have the i7 8700h version ... i used the latest efi. bluetooth and wifi not working, can you help me with bluetooth? thank you

**Comment by Salvo092000** [comment]
*sorry 8750h... it's mojave

**Comment by VitalyArt** [comment]
> *sorry 8750h... it's mojave

How did you install Mojave? I was only able to install Catalina, but it doesn't work well

**Comment by Salvo092000** [comment]
i created the USB with TINU and i used this EFI

**Comment by johnnync13** [comment]
the bluetooth kext not are on the lastest releases...

**Comment by johnnync13** [comment]
See the latest releases
