### ISSUE TITLE
efioc

### ISSUE THREAD

**Issue by yiseni** [johnnync13/XiaomiGaming#37]
Black screen with EFIOC boot.

**Comment by johnnync13** [comment]
take photo or add log

**Comment by yiseni** [comment]
I think I have solved the problem.

**Comment by yiseni** [comment]
But now the problem is that the touchpad and brightness key cannot be used with opencore. Can you solve it? thanks

**Comment by johnnync13** [comment]
@yiseni in clover works?

**Comment by yiseni** [comment]
Yes, everything works fine in clover

**Comment by johnnync13** [comment]
@yiseni what bios do you have?

**Comment by yiseni** [comment]
@johnnync13  Same under 0402 and 0604

**Comment by johnnync13** [comment]
https://github.com/johnnync13/XiaomiGaming/releases/tag/v6.3.4 @yiseni Try two versions clover and OC

**Comment by yiseni** [comment]
@johnnync13  OK,I will try it, thank you very much

**Comment by johnnync13** [comment]
@yiseni tell me something soon, and do you boot with OC without problems?

**Comment by yiseni** [comment]
@johnnync13  Yes, now it can be used normally, but there are still some small problems to be solved, because I am i5-8300h, I need to make a new copy of mine according to your oc
