### ISSUE TITLE
Backlight

### ISSUE THREAD

**Issue by yiseni** [johnnync13/XiaomiGaming#42]
The latest version of OC restarts without backlight

**Comment by johnnync13** [comment]
@yiseni in clover works well?

**Comment by yiseni** [comment]
@johnnync13  Yes clover is ok .

**Comment by johnnync13** [comment]
@yiseni tell me soon if this is resolved https://github.com/johnnync13/XiaomiGaming/releases/tag/v6.5.2

**Comment by yiseni** [comment]
OK,i well try

**Comment by yiseni** [comment]
The problem remains, when I use version 6.4.2, everything works fine @johnnync13

**Comment by johnnync13** [comment]
@yiseni I rebase efioc with these version and I will update all

**Comment by yiseni** [comment]
OK
