### ISSUE TITLE
Unkown Error When Booting From Install Media

### ISSUE THREAD

**Issue by MykaMart** [johnnync13/XiaomiGaming#43]
After loading the EFI folder onto the EFI partition of the High Sierra Install USB and using it to load the bootoader on my Xiaomi Gaming Laptop.

After selecting the install media the boatloader registers an unkown error with a 'no' symbol  (screenshot attached). Is there a error log file generated that I can reference so I can determine what the issue is?

![install_media_startup](https://user-images.githubusercontent.com/31222436/79046593-923edd80-7bd7-11ea-891d-c6a7e7c48cde.jpg)

**Comment by johnnync13** [comment]
@MykaMart this efi is only compatible with Mojave or catalina
