### ISSUE TITLE
stuck on Logo with OC

### ISSUE THREAD

**Issue by xiaoziguys** [johnnync13/XiaomiGaming#44]
BIOS: 0604
CFG UNLOCKED
Catalina 10.15.4
I used the latest release 
When I use clover, I found the bright controller doesn't work and AppleALC was not working as well.
but when I switched to OC, I stuck on Apple Logo
![9BA7BC1B0DC57B0E696A6A4A0A21B215](https://user-images.githubusercontent.com/9974143/79425703-ad08bc00-7ff4-11ea-9512-2c084db55b73.JPG)

**Comment by johnnync13** [comment]
Yes, OC not working at the moment...

**Comment by johnnync13** [comment]
try the last release
