### ISSUE TITLE
Help support Asus Vivobook PRO N580GD

### ISSUE THREAD

**Issue by megasoft78** [johnnync13/XiaomiGaming#45]
Hi,
I'm new to Hackintosh world and I'm looking to make Catalina working on my Asus Vivobook PRO N580GD.
https://www.asus.com/Laptops/ASUS-VivoBook-Pro-15-N580GD/specifications/

I already have everything working with the attached EFI.
[EFI.zip](https://github.com/johnnync13/XiaomiGaming/files/4509994/EFI.zip)
The main issue I have is graphics acceleration.
Because the CPU seems exactly the same as yours "Intel® Core™ i7 8750H", do you mind to help me a bit to understand what to change in the config.plist to make it working?
It's a problem with framebuffer.

Thank in advance. :)

**Comment by johnnync13** [comment]
https://github.com/dortania

**Comment by megasoft78** [comment]
Thank you!
I'll look into it.
