### ISSUE TITLE
Works on Mac Os Catalina?

### ISSUE THREAD

**Issue by dimusa6** [johnnync13/XiaomiGaming#46]
Hi! I used EFI with lastest commit that you push, but when I try to install it (with Mac Os Journaled or APFS format), it never finish and always reboot before finish the installation.
Also EFIOC didn't boot. Can you help me? Need I to change any bios settings? 

Thanks so much!

**Comment by johnnync13** [comment]
Sorry, try the last release

**Comment by dimusa6** [comment]
Same issue with Clover, when is 2 minutes to finish, it rebooted. I have i7-8750h and 1050 Ti specs with BIOS that you include in releases, so I don't know what's happening.
Also sometimes when it's trying to boot up the installer, it reboots too

**Comment by johnnync13** [comment]
use clover!

**Comment by dimusa6** [comment]
I tried with two method Clover and OC.
And with Clover I have same issue as I had yesterday, The installation install it normally and when it need 2 minutes to finish, the laptop reboot without finish the installation and I don't know why. I can record a video to see it or something similar if you want

**Comment by dimusa6** [comment]
I saw other people with my problem in differents laptop:
https://www.tonymacx86.com/threads/msi-gs65-installer-freezes-at-about-2-minutes-remaining.263797/

I tried adding EmuVariableUefi-64.efi to your EFI Clover folder and now it didn't reboot but it freezed. Any ideas about how solve that? Thanks

**Comment by johnnync13** [comment]
@dimusa6 i don't have this laptop. I have a spanish community on telegram that they send me feedback, but only one have this laptop and not know hackintool tools and skills... I can't do magic

**Comment by dimusa6** [comment]
Can you give me the link of the community please? I searched for it but I didn't found. Thank so much for your effort!

**Comment by johnnync13** [comment]
https://t.me/HackingtoshXiaomi
