### ISSUE TITLE
Gaming Laptop with 9th-gen CPU also works perfectly!

### ISSUE THREAD

**Issue by gbowsky** [johnnync13/XiaomiGaming#47]

**Comment by emilioApuzzo** [comment]
hello I am interested in buying this Notebook with 9 gen processor, could you tell me if Xcode and devices simulators work well ?

**Comment by gbowsky** [comment]
yikes!

чт, 28 мая 2020 г. в 04:05, emilioApuzzo <notifications@github.com>:

**Comment by Remmed96** [comment]
Thank you very much for the information, did you use only this repository or did you also use files from other parts ?

**Comment by gbowsky** [comment]
only from this repo.

пт, 29 мая 2020 г., 2:39 AM Remmed96 <notifications@github.com>:

**Comment by Remmed96** [comment]
Thanks for the info, I will definitely buy this notebook, have you tried to make benchmarks ? Is the performance similar between Windows and MacOS? (Obviously taking into account that nvidia graphics on mac does not work)

**Comment by Remmed96** [comment]
Sorry if I'm filling you in with questions but could you also tell me more or less how long the battery lasts on MacOS ?

**Comment by gbowsky** [comment]
I don't remember how long battery lasts, but it's shorter than on Windows
(for better results i think we need patched bios with unlocked cfg lock).

Also another thing I noticed what laptop on macOS generates less heat while
on battery.

And last thing is about hidpi scaling patch in guide, i don't recommend it,
because it causing flickering artifacts on 72hz mode, and you'll actually
need to use voiceover to revert settings.

пт, 29 мая 2020 г., 1:41 PM Remmed96 <notifications@github.com>:

**Comment by Remmed96** [comment]
Okay, thank you very much for the warning. I have a few more questions, thank you again for your help.
Have you noticed other "bugs" like this one? 
Have you used the guide with Clover or OpenCore ?
Does the display reach 144 Hz with MacOS ? 
I should use this notebook for coding, what do you think of the screen ? Do you think it's ok for long time use or it makes your eyes tired ?

**Comment by gbowsky** [comment]
Sorry for long answers. Display reaches 144hz with macOS. I used clover method. Other bugs like this weren't noticed. I can't tell big difference between Windows and macOS for coding, but having *nix environment is nice.

macOS nice, but I think it feels much more better on Apple-device with your finger tips.
Also I noticed what touchpad works and feels really nice (exactly like on Apple-devices) but you'll have to turn off pressure detection (it doesn't works and makes touchpad unusable).

I'm using Windows because I'm mostly working with video editing and graphic design (also coding anyway) and sometime play games.

And another last thing. HDMI won't work, because it attached to dedicated GPU.

**Comment by johnnync13** [comment]
yes! HDMI not works like other laptops, because the HDMI lines is connect by DGPU.
So, I need betatesters to migrate this EFI to OC

**Comment by Remmed96** [comment]
@gbowsky Thank you so much for your help.
@johnnync13 I haven't bought this laptop yet, but as soon as I do, I'll let you know. I'm thinking of buying it next month.

**Comment by johnnync13** [comment]
@Remmed96 i tell you to buy new laptops. If you want to have good igpu, wait for tiger lake

**Comment by Remmed96** [comment]
Okok I'll consider that too. Thanks.
