### ISSUE TITLE
我使用了您的efi，但是hdmi和typec都无法使用

### ISSUE THREAD

**Issue by huangssssx** [johnnync13/XiaomiGaming#49]
我使用了您的efi，但是hdmi和typec都无法使用，type-c插上就重启，这个问题不知道是否可以解决一下~

**Comment by johnnync13** [comment]
first of all, use English to post. 
Secondly, yes it is can be fixed. But I don't have this laptop, so in community on telegram, one person only have this laptop, so I need betatesters

**Comment by huangssssx** [comment]
sorry，I thought you were Chinese. You know, xiaomi games are not widely used in China，I have solved the problem. Thank you all the same
