### ISSUE TITLE
I have some problems whit Clover Configuration

### ISSUE THREAD

**Issue by xymoc** [johnnync13/XiaomiGaming#5]
I am from China. English is very bad, these sentences are from Google Translate. I have been researching this Game computer recently, but I have encountered some problems, such as:

- NVIDIA GTX1060 Standalone graphics cannot be driven.
- Can't wake up the computer after computer sleep.
- The touchpad does not support gestures.
- WIFI cannot be used.
- Bluetooth can only be used when Windows restart to MacOS.

If can get your help, I can provide the Clover file I use for now.

**Comment by johnnync13** [comment]
@xymoc macOS is not compatible with intel hardware(wifi, bluetooth), some devices( like card reader) and optimus nvidia technology
