### ISSUE TITLE
Need help to mapping Type-c USB 3.0 USB 2.0

### ISSUE THREAD

**Issue by johnnync13** [johnnync13/XiaomiGaming#50]

**Comment by RFyre00** [comment]
Can you help me with getting HDMI to work? no output what so ever. For Acer Triton 500 i7 8750h RTX 2060. I have tried Type-c( also thunderbolt) to HDMI too not working. Your help would be much appreciated.

**Comment by johnnync13** [comment]
@RFyre00 on some laptops hdmi works only with dgpu

**Comment by LittleTurtle2333** [comment]
The usb-c of clover can be connected to an external display, but oc can't

**Comment by LittleTurtle2333** [comment]
But using a intel graphics gpu

**Comment by RFyre00** [comment]
Are you sure type-c on clover gets HDMI? However, it is an Acer triton 500 with rtx 2060 only has one type-c  port with thunderbolt 3 too, while using windows if you disable dgpu nothing works only internal display works. If it really works on clover i will redo everything. Btw will clover be absolute someday?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Kurokitu** [comment]
![image](https://user-images.githubusercontent.com/19619713/90085827-86148980-dd4b-11ea-9a6e-de592c24d824.png)
