### ISSUE TITLE
XIAOMI GAMING 2019EDITION

### ISSUE THREAD

**Issue by handsomebroB** [johnnync13/XiaomiGaming#51]
can i use this EFI file on 2019 edition which cpu 9750h and gpu rtx2060, thanks man!

**Comment by johnnync13** [comment]
It is possible i think. Try it

**Comment by handsomebroB** [comment]
it seems everything works fine but the brightness key don't work, how could i do?

**Comment by handsomebroB** [comment]
and the hdmi video doesn't work

**Comment by handsomebroB** [comment]
and when using opencore loading windows ,the audio doesn't work

**Comment by johnnync13** [comment]
HDMI is by nvidia. And nvidia is not compatible with macOS

**Comment by johnnync13** [comment]
The audio is not good mapped. There is a tutorial to do but you need Linux
