### ISSUE TITLE
xiaomi mi gaming laptop 2019 version

### ISSUE THREAD

**Issue by MrBlamz** [johnnync13/XiaomiGaming#52]
I searched everywhere and could not find anything related. Does the 2019 version (i7-9750h and rtx 2060) works with this repo?
Thanks in advance and sorry if this is not the right place to ask this.

**Comment by MrBlamz** [comment]
> @MrBlamz just try it
Sorry. I forgot to tell that i am looking to buy this notebook. I don´t physically own it.

**Comment by VitalyArt** [comment]
https://github.com/johnnync13/XiaomiGaming/issues/51
https://github.com/johnnync13/XiaomiGaming/issues/47

**Comment by MrBlamz** [comment]
> #51
> #47

Thank you.
