### ISSUE TITLE
Trackpad and Brightness Key is not working

### ISSUE THREAD

**Issue by eilidan** [johnnync13/XiaomiGaming#54]
Hi there，i am a studient from china. Same as you ，i am in favor of Hackintosh. Recently i found your OC project for xiaomigaming desktop. Having tested this EFI for a few days i found some problems.
Trackpad and Brightness key is not working for i5 8300h.
Can you help me solve it？ Thanks for your contribution.

**Comment by johnnync13** [comment]
trackpad works well. For fix Brightness is do some change for variables, but i don´t have this laptop

**Comment by eilidan** [comment]
> trackpad works well. For fix Brightness is do some change for variables, but i don´t have this laptop
> 
> 

A friend who has the same device told me his trackpad works well. but i tried many times it still can not find trackpad. Anyway i wonder if you could teach me how to fix brightness.  thanks

**Comment by eilidan** [comment]
> trackpad works well. For fix Brightness is do some change for variables, but i don´t have this laptop
> 
> 
Can it be caused by different manufacturers of trackpad？

**Comment by LittleTurtle2333** [comment]
My touchpad is perfect

**Comment by eilidan** [comment]
> My touchpad is perfect

what is your system version？ maybe it works perfect on macOS 10.15

**Comment by LittleTurtle2333** [comment]
> > My touchpad is perfect
> 
> what is your system version？ maybe it works perfect on macOS 10.15

10.15.5

**Comment by eilidan** [comment]
> > > My touchpad is perfect
> > 
> > what is your system version？ maybe it works perfect on macOS 10.15
> 
> 10.15.5
That is right . My friend‘s device has perfect trackpad and his version is also 10.15.5

**Comment by eilidan** [comment]
> My touchpad is perfect

我们两个中国人为啥要用英语😂
