### ISSUE TITLE
I want to help fix the brightness adjustment shortcut

### ISSUE THREAD

**Issue by Kurokitu** [johnnync13/XiaomiGaming#58]
The machine I'm using is Xiaomi gaming i7-8750h.
I can try to test and fix FN adjust brightness, but I don't know how to fix ACPI.
I would like to ask in which file did you patch FN?

**Comment by shomerchang** [comment]
我是OC引导。
刚弄的，本机测试没问题
代码放在config里 ACPI->Patch
SSDT-FN.aml替换原来的
`
<dict>
				<key>Comment</key>
				<string>change Method(__Q0F,0,N) to XQ0F</string>
				<key>Count</key>
				<integer>0</integer>
				<key>Enabled</key>
				<true/>
				<key>Find</key>
				<data>X1EwRg==</data>
				<key>Limit</key>
				<integer>0</integer>
				<key>Mask</key>
				<data></data>
				<key>OemTableId</key>
				<data></data>
				<key>Replace</key>
				<data>WFEwRg==</data>
				<key>ReplaceMask</key>
				<data></data>
				<key>Skip</key>
				<integer>0</integer>
				<key>TableLength</key>
				<integer>0</integer>
				<key>TableSignature</key>
				<data>RFNEVA==</data>
			</dict>
			<dict>
				<key>Comment</key>
				<string>change Method(_Q10,0,N) to XQ10</string>
				<key>Count</key>
				<integer>0</integer>
				<key>Enabled</key>
				<true/>
				<key>Find</key>
				<data>X1ExMA==</data>
				<key>Limit</key>
				<integer>0</integer>
				<key>Mask</key>
				<data></data>
				<key>OemTableId</key>
				<data></data>
				<key>Replace</key>
				<data>WFExMA==</data>
				<key>ReplaceMask</key>
				<data></data>
				<key>Skip</key>
				<integer>0</integer>
				<key>TableLength</key>
				<integer>0</integer>
				<key>TableSignature</key>
				<data>RFNEVA==</data>
			</dict>
`

[SSDT-FN.aml.zip](https://github.com/johnnync13/XiaomiGaming/files/4977940/SSDT-FN.aml.zip)

**Comment by shomerchang** [comment]
我是OC引导的，本机测试没问题 fn+f4,f5

下面代码添加到config, ACPI->Patch下
[acpi-patch-fn.txt](https://github.com/johnnync13/XiaomiGaming/files/4977963/acpi-patch-fn.txt)

SSDT-FN.aml替换掉原来的 就可以了
[SSDT-FN.aml.zip](https://github.com/johnnync13/XiaomiGaming/files/4977957/SSDT-FN.aml.zip)

**Comment by eilidan** [comment]
亲测楼上的方法有效。本人i5 8300 OC引导。

**Comment by Kurokitu** [comment]
非常感谢，我刚好已经提交了big sur的分支合并，等待管理员同意之后就可以出现在本项目了

**Comment by Kurokitu** [comment]
> 我是OC引导的bigsur beta3，刚弄好的亮度调节快捷键，本机测试没问题 fn+f4,f5
> 
> 下面代码添加到config, ACPI->Patch下
> [acpi-patch-fn.txt](https://github.com/johnnync13/XiaomiGaming/files/4977963/acpi-patch-fn.txt)
> 
> SSDT-FN.aml替换掉原来的 就可以了
> [SSDT-FN.aml.zip](https://github.com/johnnync13/XiaomiGaming/files/4977957/SSDT-FN.aml.zip)

询问一下能集成在项目里吗，我会注明的

**Comment by shomerchang** [comment]
> > 我是OC引导的bigsur beta3，刚弄好的亮度调节快捷键，本机测试没问题 fn+f4,f5
> > 下面代码添加到config, ACPI->Patch下
> > [acpi-patch-fn.txt](https://github.com/johnnync13/XiaomiGaming/files/4977963/acpi-patch-fn.txt)
> > SSDT-FN.aml替换掉原来的 就可以了
> > [SSDT-FN.aml.zip](https://github.com/johnnync13/XiaomiGaming/files/4977957/SSDT-FN.aml.zip)
> 
> 询问一下能集成在项目里吗，我会注明的

没问题

**Comment by Kurokitu** [comment]
> > > 我是OC引导的bigsur beta3，刚弄好的亮度调节快捷键，本机测试没问题 fn+f4,f5
> > > 下面代码添加到config, ACPI->Patch下
> > > [acpi-patch-fn.txt](https://github.com/johnnync13/XiaomiGaming/files/4977963/acpi-patch-fn.txt)
> > > SSDT-FN.aml替换掉原来的 就可以了
> > > [SSDT-FN.aml.zip](https://github.com/johnnync13/XiaomiGaming/files/4977957/SSDT-FN.aml.zip)
> > 
> > 
> > 询问一下能集成在项目里吗，我会注明的
> 
> 没问题

好的，非常感谢

**Comment by Kurokitu** [comment]
@johnnync13 FN key adjustment backlight has been fixed, and additional Big Sur test EFI has been added

**Comment by Kurokitu** [comment]
> > > 我是OC引导的bigsur beta3，刚弄好的亮度调节快捷键，本机测试没问题 fn+f4,f5
> > > 下面代码添加到config, ACPI->Patch下
> > > [acpi-patch-fn.txt](https://github.com/johnnync13/XiaomiGaming/files/4977963/acpi-patch-fn.txt)
> > > SSDT-FN.aml替换掉原来的 就可以了
> > > [SSDT-FN.aml.zip](https://github.com/johnnync13/XiaomiGaming/files/4977957/SSDT-FN.aml.zip)
> > 
> > 
> > 询问一下能集成在项目里吗，我会注明的
> 
> 没问题

你好，能再问一下，你的声卡有时候会出现开机不驱动的情况吗，我经常出现

**Comment by johnnync13** [comment]
if you fix it try to do pull request

**Comment by eilidan** [comment]
> > > > 我是OC引导的bigsur beta3，刚弄好的亮度调节快捷键，本机测试没问题 fn+f4,f5
> 
> > > > 下面代码添加到config, ACPI->Patch下
> 
> > > > [acpi-patch-fn.txt](https://github.com/johnnync13/XiaomiGaming/files/4977963/acpi-patch-fn.txt)
> 
> > > > SSDT-FN.aml替换掉原来的 就可以了
> 
> > > > [SSDT-FN.aml.zip](https://github.com/johnnync13/XiaomiGaming/files/4977957/SSDT-FN.aml.zip)
> 
> > > 
> 
> > > 
> 
> > > 询问一下能集成在项目里吗，我会注明的
> 
> > 
> 
> > 没问题
> 
> 
> 
> 你好，能再问一下，你的声卡有时候会出现开机不驱动的情况吗，我经常出现

我的也经常有这样的情况。你不是一个人。

**Comment by shomerchang** [comment]
> > > > 我是OC引导的bigsur beta3，刚弄好的亮度调节快捷键，本机测试没问题 fn+f4,f5
> > > > 下面代码添加到config, ACPI->Patch下
> > > > [acpi-patch-fn.txt](https://github.com/johnnync13/XiaomiGaming/files/4977963/acpi-patch-fn.txt)
> > > > SSDT-FN.aml替换掉原来的 就可以了
> > > > [SSDT-FN.aml.zip](https://github.com/johnnync13/XiaomiGaming/files/4977957/SSDT-FN.aml.zip)
> > > 
> > > 
> > > 询问一下能集成在项目里吗，我会注明的
> > 
> > 
> > 没问题
> 
> 你好，能再问一下，你的声卡有时候会出现开机不驱动的情况吗，我经常出现

声卡还好吧，碰到过几次，但不是经常
