### ISSUE TITLE
The sound card driver often fails

### ISSUE THREAD

**Issue by Kurokitu** [johnnync13/XiaomiGaming#59]
![image](https://user-images.githubusercontent.com/19619713/88535484-8f5be180-d03c-11ea-8d91-20b79615f95e.png)

Sometimes the sound card driver works and sometimes it doesn't work

**Comment by Kurokitu** [comment]
This problem has existed for a long time, and it seems that all kinds of methods I have tried have no effect

**Comment by johnnync13** [comment]
to fix audio should fix by linux and then ported to applealc https://blog.daliansky.net/Use-AppleALC-sound-card-to-drive-the-correct-posture-of-AppleHDA.html

**Comment by Kurokitu** [comment]
OK, I'll try

**Comment by johnnync13** [comment]
I tried to do it but being in Chinese it was difficult for me in the end I was not successful

**Comment by shomerchang** [comment]
> This problem has existed for a long time, and it seems that all kinds of methods I have tried have no effect

这个应该是蓝牙驱动的问题吧，你也是用的自带的蓝牙吧，有线耳机这块不会卡，我用蓝牙到这块就会卡住。不过游戏本的声卡驱动还是有点问题，只能用内置mic录音，耳机的mic不行, 我也曾尝试解决一下，结果 弄一半实在弄不下去了 有点复杂……

**Comment by johnnync13** [comment]
for bluetooth is this kext https://github.com/OpenIntelWireless/IntelBluetoothFirmware

**Comment by shomerchang** [comment]
> for bluetooth is this kext https://github.com/OpenIntelWireless/IntelBluetoothFirmware

ok, I'll try it later

**Comment by Kurokitu** [comment]
> > This problem has existed for a long time, and it seems that all kinds of methods I have tried have no effect
> 
> 这个应该是蓝牙驱动的问题吧，你也是用的自带的蓝牙吧，有线耳机这块不会卡，我用蓝牙到这块就会卡住。不过游戏本的声卡驱动还是有点问题，只能用内置mic录音，耳机的mic不行, 我也曾尝试解决一下，结果 弄一半实在弄不下去了 有点复杂……

不是，现在的问题不是蓝牙耳机，而是音频驱动完全失效了

**Comment by Kurokitu** [comment]
> > This problem has existed for a long time, and it seems that all kinds of methods I have tried have no effect
> 
> 这个应该是蓝牙驱动的问题吧，你也是用的自带的蓝牙吧，有线耳机这块不会卡，我用蓝牙到这块就会卡住。不过游戏本的声卡驱动还是有点问题，只能用内置mic录音，耳机的mic不行, 我也曾尝试解决一下，结果 弄一半实在弄不下去了 有点复杂……

我们需要制作一个合适小米游戏本的AppleALC仿冒驱动

**Comment by Kurokitu** [comment]
> > This problem has existed for a long time, and it seems that all kinds of methods I have tried have no effect
> 
> 这个应该是蓝牙驱动的问题吧，你也是用的自带的蓝牙吧，有线耳机这块不会卡，我用蓝牙到这块就会卡住。不过游戏本的声卡驱动还是有点问题，只能用内置mic录音，耳机的mic不行, 我也曾尝试解决一下，结果 弄一半实在弄不下去了 有点复杂……

我刚刚研究了一下Johnny发给我的中文文章发现极其复杂

**Comment by johnnync13** [comment]
https://github.com/acidanthera/AppleALC/wiki/Adding-codec-support

**Comment by shomerchang** [comment]
> > > This problem has existed for a long time, and it seems that all kinds of methods I have tried have no effect
> > 
> > 
> > 这个应该是蓝牙驱动的问题吧，你也是用的自带的蓝牙吧，有线耳机这块不会卡，我用蓝牙到这块就会卡住。不过游戏本的声卡驱动还是有点问题，只能用内置mic录音，耳机的mic不行, 我也曾尝试解决一下，结果 弄一半实在弄不下去了 有点复杂……
> 
> 不是，现在的问题不是蓝牙耳机，而是音频驱动完全失效了

你的layout-id是多少，我是99 没有问题，刚试了最新的蓝牙驱动， 不卡了，不过切换到输入那界面，输入选蓝牙，输出的音质会变差很多

**Comment by Kurokitu** [comment]
> > > > This problem has existed for a long time, and it seems that all kinds of methods I have tried have no effect
> > > 
> > > 
> > > 这个应该是蓝牙驱动的问题吧，你也是用的自带的蓝牙吧，有线耳机这块不会卡，我用蓝牙到这块就会卡住。不过游戏本的声卡驱动还是有点问题，只能用内置mic录音，耳机的mic不行, 我也曾尝试解决一下，结果 弄一半实在弄不下去了 有点复杂……
> > 
> > 
> > 不是，现在的问题不是蓝牙耳机，而是音频驱动完全失效了
> 
> 你的layout-id是多少，我是99 没有问题，刚试了最新的蓝牙驱动， 不卡了，不过切换到输入那界面，输入选蓝牙，输出的音质会变差很多

一样99，但有时就是会失效

**Comment by Kurokitu** [comment]
I find that it seems to be caused by this extension
https://github.com/johnnync13/XiaomiGaming/blob/master/README.md#optional-hackintosh-combojack-how-to

**Comment by shomerchang** [comment]
> > > > > This problem has existed for a long time, and it seems that all kinds of methods I have tried have no effect
> > > > 
> > > > 
> > > > 这个应该是蓝牙驱动的问题吧，你也是用的自带的蓝牙吧，有线耳机这块不会卡，我用蓝牙到这块就会卡住。不过游戏本的声卡驱动还是有点问题，只能用内置mic录音，耳机的mic不行, 我也曾尝试解决一下，结果 弄一半实在弄不下去了 有点复杂……
> > > 
> > > 
> > > 不是，现在的问题不是蓝牙耳机，而是音频驱动完全失效了
> > 
> > 
> > 你的layout-id是多少，我是99 没有问题，刚试了最新的蓝牙驱动， 不卡了，不过切换到输入那界面，输入选蓝牙，输出的音质会变差很多
> 
> 一样99，但有时就是会失效

我看了你上传的config, 有些东西没必要加载， 我把我用的贴上来，你可以对比一下
[config.plist.zip](https://github.com/johnnync13/XiaomiGaming/files/4989829/config.plist.zip)

**Comment by Kurokitu** [comment]
> > > > > > This problem has existed for a long time, and it seems that all kinds of methods I have tried have no effect
> > > > > 
> > > > > 
> > > > > 这个应该是蓝牙驱动的问题吧，你也是用的自带的蓝牙吧，有线耳机这块不会卡，我用蓝牙到这块就会卡住。不过游戏本的声卡驱动还是有点问题，只能用内置mic录音，耳机的mic不行, 我也曾尝试解决一下，结果 弄一半实在弄不下去了 有点复杂……
> > > > 
> > > > 
> > > > 不是，现在的问题不是蓝牙耳机，而是音频驱动完全失效了
> > > 
> > > 
> > > 你的layout-id是多少，我是99 没有问题，刚试了最新的蓝牙驱动， 不卡了，不过切换到输入那界面，输入选蓝牙，输出的音质会变差很多
> > 
> > 
> > 一样99，但有时就是会失效
> 
> 我看了你上传的config, 有些东西没必要加载， 我把我用的贴上来，你可以对比一下
> [config.plist.zip](https://github.com/johnnync13/XiaomiGaming/files/4989829/config.plist.zip)

I tried any possibility and referred to your profile, but it didn't work

**Comment by shomerchang** [comment]
> > > > > > > This problem has existed for a long time, and it seems that all kinds of methods I have tried have no effect
> > > > > > 
> > > > > > 
> > > > > > 这个应该是蓝牙驱动的问题吧，你也是用的自带的蓝牙吧，有线耳机这块不会卡，我用蓝牙到这块就会卡住。不过游戏本的声卡驱动还是有点问题，只能用内置mic录音，耳机的mic不行, 我也曾尝试解决一下，结果 弄一半实在弄不下去了 有点复杂……
> > > > > 
> > > > > 
> > > > > 不是，现在的问题不是蓝牙耳机，而是音频驱动完全失效了
> > > > 
> > > > 
> > > > 你的layout-id是多少，我是99 没有问题，刚试了最新的蓝牙驱动， 不卡了，不过切换到输入那界面，输入选蓝牙，输出的音质会变差很多
> > > 
> > > 
> > > 一样99，但有时就是会失效
> > 
> > 
> > 我看了你上传的config, 有些东西没必要加载， 我把我用的贴上来，你可以对比一下
> > [config.plist.zip](https://github.com/johnnync13/XiaomiGaming/files/4989829/config.plist.zip)
> 
> I tried any possibility and referred to your profile, but it didn't work

try to remove the codeccommand.kext from your config.plist

**Comment by Kurokitu** [comment]
> > > > > > > > This problem has existed for a long time, and it seems that all kinds of methods I have tried have no effect
> > > > > > > 
> > > > > > > 
> > > > > > > 这个应该是蓝牙驱动的问题吧，你也是用的自带的蓝牙吧，有线耳机这块不会卡，我用蓝牙到这块就会卡住。不过游戏本的声卡驱动还是有点问题，只能用内置mic录音，耳机的mic不行, 我也曾尝试解决一下，结果 弄一半实在弄不下去了 有点复杂……
> > > > > > 
> > > > > > 
> > > > > > 不是，现在的问题不是蓝牙耳机，而是音频驱动完全失效了
> > > > > 
> > > > > 
> > > > > 你的layout-id是多少，我是99 没有问题，刚试了最新的蓝牙驱动， 不卡了，不过切换到输入那界面，输入选蓝牙，输出的音质会变差很多
> > > > 
> > > > 
> > > > 一样99，但有时就是会失效
> > > 
> > > 
> > > 我看了你上传的config, 有些东西没必要加载， 我把我用的贴上来，你可以对比一下
> > > [config.plist.zip](https://github.com/johnnync13/XiaomiGaming/files/4989829/config.plist.zip)
> > 
> > 
> > I tried any possibility and referred to your profile, but it didn't work
> 
> try to remove the codeccommand.kext from your config.plist

thank you! After you disable it, the sound card works!
