### ISSUE TITLE
关于音频

### ISSUE THREAD

**Issue by yiseni** [johnnync13/XiaomiGaming#60]
我已经适配小米八代游戏本的声卡驱动

**Comment by Kurokitu** [comment]
你好，请问是如何解决的呢

**Comment by yiseni** [comment]
根据声卡节点自己进行了驱动适配，如果需要，我可以提供修改后源码。

**Comment by Kurokitu** [comment]
好的，那麻烦你了，请问可以集成在本项目中吗

**Comment by yiseni** [comment]
我不太会使用github，可加我Q1459819034

**Comment by shomerchang** [comment]
> 我已经适配小米八代游戏本的声卡驱动

厉害了，期待

**Comment by johnnync13** [comment]
english please, if not I will close the post
