### ISSUE TITLE
Realtek Card Reader/读卡器

### ISSUE THREAD

**Issue by eilidan** [johnnync13/XiaomiGaming#64]
黑苹果一直没有读卡器的驱动。前几天发现sinetek-rtsx.kext可以成功驱动，但是存在读取速度慢的问题。有没有大佬可以研究研究。
Realtek Card Reader has not been supported for a long time. I found a kext which can successfully identify SD cards. But there still some bugs. The read/write speed is too much lower than the speed on windows. Is there anyone who can fix this.
[Sinetek-rtsx.kext.zip](https://github.com/johnnync13/XiaomiGaming/files/5040238/Sinetek-rtsx.kext.zip)
https://github.com/sinetek/Sinetek-rtsx

**Comment by Kurokitu** [comment]
This cannot be solved for the time being, please wait for better development
