### ISSUE TITLE
v6.6.6无法正常引导

### ISSUE THREAD

**Issue by SunHuilong** [johnnync13/XiaomiGaming#66]
[v6.6.6](https://github.com/johnnync13/XiaomiGaming/releases/tag/v.6.6.6)无法正常引导安装，但是可以引导启动；[v6.6.5](https://github.com/johnnync13/XiaomiGaming/releases/tag/v6.6.5)一切正常

**Comment by eilidan** [comment]
我重装完v6.6.6不能正常引导启动系统。

**Comment by Kurokitu** [comment]
Have you ever tried to clear nvarm when upgrading boot?

**Comment by Kurokitu** [comment]
If you don't clear nvrm, you may not be able to start

**Comment by Kurokitu** [comment]
If it's still not resolved, try v6.6.7
