### ISSUE TITLE
如何解锁CFG

### ISSUE THREAD

**Issue by MrSixR** [johnnync13/XiaomiGaming#68]
你好，ru。efi文件的使用我好像有点问题，我把U盘格式化成FAT32格式后，把ru文件夹内的内容放到了U盘里，然后重启按F12启动项里并没有这个项，bios里usb启动也已打开，在朋友相同电脑上也试了，也没有反应。不知道是什么原因。
另外，6.6.6&6.6.7有引导禁行问题，我试了clean NVRAM依然不能正常进去系统

**Comment by eilidan** [comment]
把ru.efi改名成bootx64.efi放进efi/boot里能看到启动项，但是进去之后黑屏。没有界面显示

**Comment by MrSixR** [comment]
我解决了ruefi的问题,大概率是我的方法不对,再开机按F12以后U盘需要重新插拔一次,才可以看到启动选项.现在我已经成功解锁了CFG锁,调用了mac原生的电源管理.
另外,6.6.6&6.6.7的开机禁行问题我也找到了原因,在kexts文件夹里有两个itlwm文件只需删除文件名带X的即可,那并不支持八代米游本上的intel ac9560网卡.

**Comment by johnnync13** [comment]
@MrSixR fix it! How do you unlock bios?

**Comment by eilidan** [comment]
> @MrSixR fix it! How do you unlock bios?
Using a tool named ru.efi. Format an usb disk into fat32. And create an folder named “EFI” and move the ru.efi to this path EFI/boot/bootx64.efi （rename ru.efi to bootx64.efi）here to download this tool https://github.com/JamesAmiTw/ru-uefi The tool may have some bugs that your computer may need to reboot a few times to reach the GUI
