### ISSUE TITLE
Guide on how to install Mojave with this files

### ISSUE THREAD

**Issue by XipKid64** [johnnync13/XiaomiGaming#7]
Hello,

I saw your EFI files on tonymacs, and since I wanted to try hackintosh for a long try i decided to give it a go. I'd deeply appreciate it if you could point me the way to go (which arguments to use, cautions to have) so that I can hopefully install it on my machine. I'm a noob but i'd like to know more and contribute back to the community, so I believe having a machine would be a great start.

Thanks in advance, 
Diogo

**Comment by johnnync13** [comment]
@XipKid64  You should create usb installer( there are many tutorials on youtube) and put my efi. The installation use a external mouse. In first boot put my EFI in to EFI partition and reboot. Finally you rebuild kextcache with terminal: sudo kextcache -i /

**Comment by Yopli2k** [comment]
Hi, I am trying to install Mojave on this laptop model without success for many days. You say:
> You should create usb installer( there are many tutorials on youtube)

But it would help me to know something more specific. There are many programs, such as Unibest and Clover (different versions), and different MBR, GUID configurations. I have tried various combinations of usb but I can not finish the installation to the M.2 disk (maybe you install it in an SSD) it is restarted before and then when starting the disk it does not work even copying your EFI.

> In first boot put my EFI in to EFI partition and reboot.

It is not clear if you mean after you have booted correctly and on the Mojave desktop or if you have to copy the EFI before you even start booting from the disk for the first time after completing the installation.

> Finally you rebuild kextcache with terminal: sudo kextcache -i /

I understand that this process is from the console once the Mojave has been booted from the disk. But it could also be that you refer to booting the console from the installer. In general, a step by step or detailed "How to" would be very helpful. I think we are many interested in your work. And I take this opportunity to encourage you and thank you for your effort and work.
Congratulations.

**Comment by XipKid64** [comment]
> Hi, I am trying to install Mojave on this laptop model without success for many days. You say:
> 
> > You should create usb installer( there are many tutorials on youtube)
> 
> But it would help me to know something more specific. There are many programs, such as Unibest and Clover (different versions), and different MBR, GUID configurations. I have tried various combinations of usb but I can not finish the installation to the M.2 disk (maybe you install it in an SSD) it is restarted before and then when starting the disk it does not work even copying your EFI.
> 
> > In first boot put my EFI in to EFI partition and reboot.
> 
> It is not clear if you mean after you have booted correctly and on the Mojave desktop or if you have to copy the EFI before you even start booting from the disk for the first time after completing the installation.
> 
> > Finally you rebuild kextcache with terminal: sudo kextcache -i /
> 
> I understand that this process is from the console once the Mojave has been booted from the disk. But it could also be that you refer to booting the console from the installer. In general, a step by step or detailed "How to" would be very helpful. I think we are many interested in your work. And I take this opportunity to encourage you and thank you for your effort and work.
> Congratulations.

Fully agree with everything, would love to see a detailed how to or at least some more details since I've gotten no success so far. Also trying to install in the NVMe m.2 disk

**Comment by johnnync13** [comment]
PM981 SSD is not compatible with macOS @XipKid64 @Yopli2k

**Comment by XipKid64** [comment]
> PM981 SSD is not compatible with macOS @XipKid64 @Yopli2k
> Use 970 evo or 860 evo sata

In that case, can I use the internal 1TB HDD?

**Comment by johnnync13** [comment]
@XipKid64 yes! I don't have time to do tutorial. I'm Computer engineering student.. On this weeks, I have exams

**Comment by XipKid64** [comment]
> @XipKid64 yes! I don't have time to do tutorial. I'm Computer engineering student.. On this weeks, I have exams

I understand, I'm a law student and I'm also in an exam time. Thanks for the help!

**Comment by XipKid64** [comment]
> @XipKid64 yes! I don't have time to do tutorial. I'm Computer engineering student.. On this weeks, I have exams

Sorry to bother you again, just a question that came up. Is there a free m.2 port I could put an extra NVMe SSD on or would I have to remove the preinstalled SSD?

**Comment by JohnyFW** [comment]
Hello @johnnync13, thank you for specifying the M2 disk, thanks to that (**very important**) I have Mojave.
Wifi does not work (I'll search for a compatible wifi usb)  the hdmi and the bluetooth do not work for me, can you help me?
@XipKid64 This PC model has two M2 ports and one SSD.

**Comment by XipKid64** [comment]
I've read though that the Mechanical Hard Drive cable stops you from using the second m.2 port, is that right? Also, are both ports NVMe or is one of them m.2 SATA only?

**Comment by JohnyFW** [comment]
Aqui tienes una https://ibb.co/HgsZpFr
the configuration that you see does not work, it may be the M2 that is incompatible (the disk that comes by default in this laptop). I'm going to try putting the EVO disk in the second slot

**Comment by JohnyFW** [comment]
https://ibb.co/vqnCnLd
https://ibb.co/CHkCZJt
Now I have the EVO in the second MV and an SSD and it works correctly. The only problem I had with the SSD disk was that I had to lower the spindle of the SSD connector, I could not screw the second MV correctly

**Comment by johnnync13** [comment]
@JohnyFW wifi intel and bluetooth never work!

**Comment by XipKid64** [comment]
Tried formatting a partition of the HDD to APFS with no luck. The disk utility crashes and the resulting partition is unusable

**Comment by johnnync13** [comment]
Apfs is for SSD @XipKid64

**Comment by XipKid64** [comment]
Same thing with HFS+. Any type of formatting with disk utility doesn't work properly on the HDD

**Comment by johnnync13** [comment]
What problem do you have? @XipKid64

**Comment by JohnyFW** [comment]
> @JohnyFW wifi intel and bluetooth will never work!

I would appreciate it if you deleted bluetooth from your "things that work" section
What bluetooth USB model do you use to make it work?
I am very grateful for your work

**Comment by JohnyFW** [comment]
> Same thing with HFS+. Any type of formatting with disk utility doesn't work properly on the HDD

@XipKid64:

I'm use this tutorial with option 2 ( GPT one partition )
https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/

I follow the tutorial processes until I get to the step of installing MOJAVE on the USB and stop the tutorial

I copy the EFI of @johnnync13 johnny and I already have the mojave USB installer ready

on my laptop I have removed the M2 disk and replaced it with a Samsung EVO
and I changed the mechanical disk for a solid disk SSD
the installation is done on the M2 disk

**Comment by XipKid64** [comment]
> What problem do you have? @XipKid64

I've made a 64gb (also tried 96gb) partition on the mechanical HDD, which I format to exFAT. When I boot to the MacOS installer and load disk utility, I select it and click "delete", then I choose HFS+/APFS (I've tried both) and when it's "desmounting disk" it crashes to the initial menu. When I open the disk utility the drive is greyed out, clicking "mount" doesn't do anything. Not really sure what I'm doing wrong

**Comment by XipKid64** [comment]
@johnnync13 Update - I found out MacOS is very picky about partitions made outside its disk utility software. By backing up my files and formatting the whole drive to APFS (Later on I formatted most of it back to exFAT, which I reformatted to NTFS on Windows) I managed to install it and so I now have a working machine. Just a small problem though, the trackpad isn't working properly. Is there anything I can do to fix this?

**Comment by JohnyFW** [comment]
Great congratulatios, your output HDMI works?

**Comment by XipKid64** [comment]
@JohnyFW  Haven't given it a try yet since I have nothing to test it on. My main worry now is the trackpad really.

**Comment by JohnyFW** [comment]
the audio works me test select an audio output, I think they have the description changed, an internal speaker is the connector of the connector for my external speakers

**Comment by XipKid64** [comment]
@JohnyFW can you send me a picture of your BIOS screen to check how your storage disks show up?

**Comment by XipKid64** [comment]
@johnnync13 trackpad still not working, even after updating to your latest EFI. Is there something I must enable for it to work properly?

**Comment by johnnync13** [comment]
@XipKid64 https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/

**Comment by johnnync13** [comment]
@XipKid64 What version are you using?

**Comment by XipKid64** [comment]
[debug_22475.zip](https://github.com/johnnync13/XiaomiGaming/files/2753288/debug_22475.zip)
Here it is. What do you mean, Mojave version? 1.14.2

**Comment by JohnyFW** [comment]
> @JohnyFW can you send me a picture of your BIOS screen to check how your storage disks show up?
This is my bios

https://ibb.co/tXMqW5B
