### ISSUE TITLE
Choosing second SSD for macOS

### ISSUE THREAD

**Issue by Nikita0820** [johnnync13/XiaomiGaming#74]
Good evening, please tell me which second SSD do you recommend? 

For Windows, I use the bundled one: SSD Samsung PM981 256 GB (MZVLB256HAHQ). 
As I understand it is the best option for the second OS - MacOS?

I want a fast and stable experience with these 2 OS (Windows + Mac). My laptop is 1050ti, i5 8300h (2 gen). Other specs: first SSD - 256, second - i don`t use, HHD - 1TB, RAM - 8gb at first slot, second i don`t use.

Can I use HHD 1TB in my laptop to save files from these two systems?

Huge thanks for your work and efforts!

**Comment by johnnync13** [comment]
you can use nvme or sata.

**Comment by Nikita0820** [comment]
Thanks a lot for your answer! What about risks: overheating, burned out video card, problems with cooling?

**Comment by vovazubko** [comment]
These disks are my choice.

![Screenshot 2020-11-14 at 00 23 06](https://user-images.githubusercontent.com/710786/99126860-a6d0d180-260f-11eb-889e-c7e9bc0ed343.png)

**Comment by fedecarroz** [comment]
Can anyone tell me if it is possible to use at the same time 2 ssd and an hdd? Because I read in the BIOS that ssd2 and hdd can't be used together. In that case i follow this issue to choose a second ssd

**Comment by vovazubko** [comment]
I use 3 SSD (HDD replace to SSD)
They work well together.
![photo_2021-02-24_13-48-01](https://user-images.githubusercontent.com/710786/108996340-ed21dc00-76a6-11eb-87cc-c0b3d5034b5b.jpg)

**Comment by fedecarroz** [comment]
> I use 3 SSD (HDD replace to SSD)
> They work well together.
> ![photo_2021-02-24_13-48-01](https://user-images.githubusercontent.com/710786/108996340-ed21dc00-76a6-11eb-87cc-c0b3d5034b5b.jpg)

Ok perfect. I asked because of what is written on the right side of the picture you send. Thanks
