### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by Kurokitu** [johnnync13/XiaomiGaming#81]
1. The CPU does not stop working when the machine is sleeping. The CPU temperature is still very high, and the cooling of the CPU fan seems to start rarely during normal use

2. Sometimes it will wake up automatically after sleep and the error tone will appear

3. Power management can't see battery status

**Comment by xhy200606** [comment]
Sometimes power management works well ,sometimes not

**Comment by johnnync13** [comment]
Update virtualsmc.
Bluetooth kext maybe still have some problems to hibernate.
Check in RTCHibernateaware.
Update CPUFriend and data with: https://github.com/corpnewt/CPUFriendFriend

**Comment by Kurokitu** [comment]
![image](https://user-images.githubusercontent.com/19619713/97078511-473e6200-161f-11eb-84d4-f705ff31f648.png)
Does RTC refer to this option?

**Comment by Kurokitu** [comment]
I tried to update virtualsmc, but it didn't work. I don't know if it is caused by beta system or driver problem

**Comment by Kurokitu** [comment]
![image](https://user-images.githubusercontent.com/19619713/97079304-5de7b780-1625-11eb-97e1-db0f086b9c0c.png)
The touchpad doesn't work

**Comment by Kurokitu** [comment]
After the notebook is closed, the CPU temperature continues to rise in sleep state

**Comment by johnnync13** [comment]
if the battery not show on system, trackpad will not work

**Comment by Kurokitu** [comment]
![image](https://user-images.githubusercontent.com/19619713/98390377-39152a80-2090-11eb-91e4-2ea336282c67.png)

SMCBatteryManager seem to be working

**Comment by johnnync13** [comment]
Maybe VoodooI2C is still not updated to Big Sur

**Comment by Kurokitu** [comment]
> Maybe VoodooI2C is still not updated to Big Sur

I'm not sure, because sometimes SMC power management works, but sometimes it doesn't work
ACPI's power management doesn't work at all

**Comment by johnnync13** [comment]
I think because, it is possible that macbook pro version is not on virtualsmc. You can check it

**Comment by Kurokitu** [comment]
> 我认为是因为，macbook pro版本可能不在virtualsmc上。你可以检查一下

I have test, I found a problem. When the battery is turned on without power supply, the battery will display the maintenance status, but if the power is connected, the SMC can get the battery status normally

OK, I'll try to check the MAC model

**Comment by Kurokitu** [comment]
> I think because, it is possible that macbook pro version is not on virtualsmc. You can check it

I didn't find the list of versions of virtualsmc. But I set up the MacBook Pro 15,2
I think there should be no problem
But it doesn't work all the time

**Comment by Kurokitu** [comment]
I finally found the cause of the problem, and I found out that there was no ACPIBatteryManager.kext in the kext folder
🤣

**Comment by johnnync13** [comment]
@Kurokitu But if you use virtualsmc you should use SMCBatteryManager.kext

**Comment by Kurokitu** [comment]
I bought a USB Bluetooth adapter and I want to disable Intel Bluetooth. What do I need to do?

**Comment by johnnync13** [comment]
You should modify usb configuration and delete bluetooth kexts
