### ISSUE TITLE
OCS: no schema for DummyPowerManagement at 8 index, context <Quirks>

### ISSUE THREAD

**Issue by vovazubko** [johnnync13/XiaomiGaming#82]
I have this message when OC is loading.

**OCS: no schema for DummyPowerManagement at 8 index, context <Quirks>**

Please help me to fix it.
I use the latest build: 7.1.0, but replace **AirportItlwm.kext**, because it doesn't work from release.
MacOS Catalina version: 10.15.7 (19H2)

**Comment by eilidan** [comment]
This is caused by the version of OCC is lower than the EFI version.
 use the latest version of opencore configurator and open the config.plist  can solve this problem.
