### ISSUE TITLE
Mi Gaming Notebook 2019 CFG Lock

### ISSUE THREAD

**Issue by traysub** [johnnync13/XiaomiGaming#84]
I have successfully installed Catalina.  Everything is going so far, only I have a very high power consumption in battery mode.  One battery charge lasts just under an hour.
Is it possible to unlock CFG on this Model with the same Value "setup_var 0x3C 0x00" like on the 8th Generation Model?

My Specs: 9750H, RTX 2060

**Comment by zerocat7** [comment]
小米游戏本待机电池本来就不经用,不过得提一下，用grub的set_var貌似不行(我试过)可以使用ru的，而且CFG LOCK的地址不是0x3C , 应该是0x3E
The standby battery of the Mi Gaming notebook is not used originally, but I have to mention that using grub's set_var does not seem to work (I tried). You can use ru, and the address of CFG LOCK is not 0x3C, it should be 0x3E

![image](https://user-images.githubusercontent.com/30487538/99138162-986cc080-25e3-11eb-980b-0259735dcad6.png)


![image](https://user-images.githubusercontent.com/30487538/99138191-c3efab00-25e3-11eb-9e6f-ad9f03613c9c.png)

![image](https://user-images.githubusercontent.com/30487538/99138195-cc47e600-25e3-11eb-8aa7-5a09aa8f0e78.png)

RU:https://github.com/JamesAmiTw/ru-uefi

**Comment by traysub** [comment]
With ru.efi and 0x3e I have now managed it, thank you very much.

**Comment by mamatrix** [comment]
I apologize I have a xiaomi mi gaming identical to yours, I would need to know in detail how you unlocked the mi gaming, I used lamodGRUBShell.efi with setup_var 0x3c and 0x3e setup_var 1 2 and 3 without any success, you could write me here the setup commands that you have used? i'm going crazy at 1 month now
