### ISSUE TITLE
OpenCore and kexts have to be updated to work properly with macOS Big Sur's last betas. 

### ISSUE THREAD

**Issue by gbowsky** [johnnync13/XiaomiGaming#85]
macOS Big Sur is coming to be released at 10th November event. Updating OC and Kexts locally on my machine (Mi Gaming Laptop 2019) caused no issue at all.

![image](https://user-images.githubusercontent.com/36237725/98155356-27dcea00-1ee7-11eb-9279-0e01e4f63369.png)

**Comment by zerocat7** [comment]
Здравствуйте, удобно ли поделиться файлом EFI Биг Сур
Hello, is it convenient to share the EFI file of Big Sur

**Comment by johnnync13** [comment]
try the last release @zerocat7 @gbowsky
