### ISSUE TITLE
OpenCore dual boot Windows 10 boot as real hardware

### ISSUE THREAD

**Issue by vovazubko** [johnnync13/XiaomiGaming#86]
Can OpenCore boot Windows 10 without any emulations?
I want to load Win10 as real hardware, but Opencore emulate as Mac Book.
![2020-11-08_14-51-50](https://user-images.githubusercontent.com/710786/98465593-9913ea00-21d2-11eb-81e2-a9c5a6f70b64.png)

**Comment by johnnync13** [comment]
try to change platformInfo
