### ISSUE TITLE
关于CPU的变频问题

### ISSUE THREAD

**Issue by MrSixR** [johnnync13/XiaomiGaming#93]
作者你好,我是一个使用你EFI的人,我的电脑配置是i5-8300H+1060,我用了你的EFI,似乎CPU变频出现问题,用intel power gadget基本频率只有一点几,最大频率只有3左右,我觉得这在macOS上不正常的,而且在fcp导出视频的时候cpu的频率只有二点几.
你知道这如何让解决吗?

**Comment by Kurokitu** [comment]
Since this is a DSDT for i7-8750, you can modify it
