### ISSUE TITLE
Supporting 2019 i5 Mi Gamig laptop

### ISSUE THREAD

**Issue by mo999dev** [johnnync13/XiaomiGaming#96]
Hi @johnnync13 
Hope you are doing well with your study
I bought Xiaomi Mi gaming laptop from china and it will arrive within a week, and when it arrives I want to install a second SSD and install mac OS on it.
I want to know if this project support my laptop

The specs:
Intel Core i5-9300h
Nvidia GTX 1660ti ( I know it will not work )
512 SSD
8GB RAM

If it doesn't work on my laptop, could you guid me to a tutorial for it ?
Or how could I make my own copy just like you made this ?
I am a developer and have a good technical and CS skills, Especially in UNIX/Linux based systems ( I worked with Ubuntu & android ) so I think if you giuded me I can make it

Thanks a lot for your effort ❤

**Comment by johnnync13** [comment]
it should be supported, by only intel graphics

**Comment by mo999dev** [comment]
Thank you so much for the answer,
I really appreciate it

‫في الأربعاء، 9 يونيو 2021 في 1:03 ص تمت كتابة ما يلي بواسطة ‪Johnny‬‏ <‪
***@***.***‬‏>:‬
