### ISSUE TITLE
New problems in Monterey

### ISSUE THREAD

**Issue by Kurokitu** [johnnync13/XiaomiGaming#99]
- Intel Bluetooth failure
- Sound card driver failure
- When power on, the backlight fails but there is display output, so you need to use a flashlight to illuminate the screen (but it will recover after waiting for a period of time)

**Comment by maodaiyong** [comment]
> - Intel Bluetooth failure
> 
> - Sound card driver failure
> 
> - When power on, the backlight fails but there is display output, so you need to use a flashlight to illuminate the screen (but it will recover after waiting for a period of time)

可解决么？

**Comment by fedecarroz** [comment]
I have the same problem (the backlight problem) on Big Sur 11.6 with EFI folder release 7.1.5. Bluetooth and sound cards are working fine.
